// WebGame/vue-webgame/src/components/games/GuGuDan.vue
<template>
  <div>
    <h2>{{ first }} X {{ second }}</h2>
    <form @submit.prevent="onSubmit">
      <input type="number" v-model="value" placeholder="number please" />
      <button type="submit">Button</button>
    </form>
    <h2>{{ result }}</h2>
  </div>
</template>

<script>
export default {
  name: "GuGuDan",
  data() {
    return {
      first: Math.ceil(Math.random() * 9),
      second: Math.ceil(Math.random() * 9),
      value: "",
      result: "",
    };
  },
  methods: {
    onSubmit() {
      // e.preventDefault(); //@submit.prevent
      // const value = Number(this.value);
      // const result = value === this.first * this.second ? "정답" : "오답";
      // this.result = result;
      if (Number(this.value) === this.first * this.second) {
        this.result = "정답";
        this.first = Math.ceil(Math.random() * 9);
        this.second = Math.ceil(Math.random() * 9);
        this.value = "";
      } else {
        this.result = "오답";
        this.value = "";
      }
    },
  },
};
</script>

<style></style>

// WebGame/react-webgame/src/pages/GuGuDan/index.jsx
import React, { useState } from "react";
import PropTypes from "prop-types";
import Form from "../../components/Form";
import Input from "../../components/Input";
import Button from "../../components/Button";

const GuGuDan = () => {
  const [first, setFirst] = useState(Math.ceil(Math.random() * 9));
  const [second, setSecond] = useState(Math.ceil(Math.random() * 9));
  // const [number, setNumber] = useState({
  //   first: Math.ceil(Math.random() * 9),
  //   second: Math.ceil(Math.random() * 9),
  // });
  const [input, setInput] = useState("");
  const [result, setResult] = useState("");

  const onChangeFromInput = (e) => {
    setInput(e.target.value);
  };

  const onSubmitForm = (e) => {
    e.preventDefault();
    if (first === "" || second === "") {
      alert("두 수를 입력하세요.");
      return;
    } else if (first * second === parseInt(input)) {
      alert("정답입니다.");
      setResult("정답입니다.");
      setFirst(Math.ceil(Math.random() * 9));
      setSecond(Math.ceil(Math.random() * 9));
      setInput("");
    } else {
      alert("오답입니다.");
      setResult("오답입니다.");
      setInput("");
    }
  };

  return (
    <Form onSubmit={onSubmitForm}>
      <div>
        {first} X {second}
      </div>
      <Input type={"number"} placeholder={"숫자"} value={input} onChange={onChangeFromInput} />
      <Button type={"submit"}>submit</Button>
      {first * second === Number(input) ? <div>{result}</div> : <div>{result}</div>}
    </Form>
  );
};

GuGuDan.propTypes = {
  onSubmit: PropTypes.func,
  children: PropTypes.node,
};

export default GuGuDan;
